name: Portfolio

  on:
    push:
      branches: [main]


  permissions:
      pages: write
      id-token: write


  jobs:
    deploy:
      runs-on: ubuntu-latest


      environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}

      steps:
        # get access to your Portfolio code via pre-built actions
        # clones or checks out the code where this workflow is written
        # step 1
        - name: Checkout Code
          uses: actions/checkout@v4

          # setup GitHub Pages
          # step 2
        - name: setup Github Pages
          uses: actions/configure-pages@v4

          # static code artifacts
          # step 3
        - name: upload static files
          uses: actions/upload-pages-artifact@v4

          # Make page Live
          # step 4
        - naem: Deploy to Github pages
          uses: actions/deploy-pages@v4

